name: "Electron Rebuild Testing"

on: [pull_request]

jobs:
  rebuild:
    name: Run electron-rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install MagicMirror
        run: npm run install-mm
      - name: Test install electron v28
        run: npm install electron@28
      - name: Install @electron/rebuild
        run: npm install @electron/rebuild
      - name: Install some test library to be rebuilded
        run: npm install onoff node-pty
      - name: Run electron-rebuild
        run: npx electron-rebuild
        continue-on-error: false
